test:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - cd tests/ && pip install -r requirements.txt
  - python run.py -v
  artifacts:
    paths:
    - tests/report.log
